height_over_place: 0.005 # in m
set_z_up: True # Whether or not to disregard orientation of the cube pose that is not in the xy-plane

# planners: ['RRTConnectkConfigDefault']
planners: ['SPARStwokConfigDefault', 'LazyPRMstarkConfigDefault', 'RRTConnectkConfigDefault'] # [0] will be default, in order to try out

arm_straight_pose: [0, 0, 0, 0, 0, 0, 0] # joint space
start_pose: [0.50, 0.30, 1.25, 1.35, -1.57, 0.70, 0.70] # joint space
look_at_pose: [0.55, 1.35, 1.3, 1.95, -1.7, 0.50, -0.20] # joint space

start_grasp_pose_left_pos:    [0.2, 0.375, 0.55] # left corner of the table
start_grasp_pose_right_pos:   [0.2, -0.375, 0.55] # left corner of the table
# # 45 deg approach pose:
# start_grasp_pose_left_quat:   [[0.1464466,  0.3535534, -0.3535534,  0.8535534],   
#                                [0.8535534, -0.3535534, -0.3535534, -0.1464466]] # 180 deg x (locally)
# start_grasp_pose_right_quat:  [[-0.1464466, 0.3535534,  0.3535534,  0.8535534],
#                                [ 0.8535534, 0.3535534, -0.3535534,  0.1464466]]  # 180 deg x (locally)
# 30 deg approach pose:
start_grasp_pose_left_quat:   [[0.09881309,  0.23855592, -0.36955592,  0.89218691],   
                               [0.89218691, -0.36955592, -0.23855592, -0.09881309]] # 180 deg x (locally)
start_grasp_pose_right_quat:  [[-0.09881309,  0.23855592,  0.36955592,  0.89218691],
                               [ 0.89218691,  0.36955592, -0.23855592,  0.09881309]]  # 180 deg x (locally)

rotate_0: [0, 0, 0, 1] # quat
approach_ang_hor: [0, 0.382, 0,  0.923] # quat, 45deg around y

# quat, rotations around z axis in 30 deg steps
grasps: [[0, 0, 0, 1],                            # front, 0 deg z
         [1, 0, 0, 0],                            # front with gripper rotated by 180 (symmetry)
         [0, 0, 0.258819, 0.9659258],             # 30 deg z
         [0.9659258, 0.258819, 0, 0],             # 30 deg z, then 180 deg x (locally)
         [0, 0, 0.5, 0.8660254],                  # 60 deg z
         [0.8660254, 0.5, 0, 0],                  # 60 deg z, then 180 deg x (locally)
         [0, 0, 0.7071068, 0.7071068],            # left, 90 deg z
         [0.7071068, 0.7071068, 0, 0],            # left, 90 deg z, then 180 deg x (locally)
         [0, 0, 0.8660254, 0.5],                  # 120 deg z
         [0.5, 0.8660254, 0, 0],                  # 120 deg z, then 180 deg x (locally)
         [0, 0, 0.9659258, 0.258819],             # 150 deg z 
         [0.258819, 0.9659258, 0, 0],             # 150 deg z, then 180 deg x (locally)
         [0, 0, 1, 0],                            # back, 180 deg z
         [0, 1, 0, 0],                            # back, 180 deg z, then 180 deg x (locally)
         [0, 0, 0.9659258,-0.258819],             # 210 deg z
         [-0.258819, 0.9659258, 0, 0],            # 210 deg z, then 180 deg x (locally)
         [0, 0, 0.8660254, -0.5],                 # 240 deg z
         [-0.5, 0.8660254, 0, 0],                 # 240 deg z, then 180 deg x (locally)
         [0, 0, 0.7071068, 0.7071068],            # right, 270 deg z
         [0.7071068, 0.7071068, 0, 0],            # right, 270 deg z, then 180 deg x (locally)
         [0, 0, 0.5, -0.8660254],                 # 300 deg z
         [-0.8660254, 0.5, 0, 0],                 # 300 deg z, then 180 deg x (locally)
         [0, 0, 0.258819, -0.9659258],           # 330 deg z
         [-0.9659258, 0.258819, 0, 0]]            # 330 deg z, then 180 deg x (locally)           

planning_time: 5.0 # s
num_planning_attempts: 10
