gripper: 
  joint_names_left: ['gripper_left_finger_joint']
  joint_names_right: ['gripper_right_finger_joint']
  gripper_closed: [0.5] # dm
  gripper_opened: [0.0] # dm
  grasp_offset_x: 0.02 # m
  grasp_offset_z: 0.02 # m